######################## default configuration ####################
baseURL = "https://nullshots.com"
title = "Developer Vlog"
theme = "reporter"
# post pagination
paginate = "7"
# post excerpt
summaryLength = "60"
# google analytics
googleAnalytics = "" 
# disqus short name https://disqus.com
disqusShortname = "nullshots-com"
# disable language
disableLanguages = []

# webp image quality
[imaging]
quality = 100


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe= true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"