################################### English language #####################################
[en]
languageName = "en"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
copyright = "❤️ Made with Love ❤️"